import { useMemo, useState } from "react";
import type { ReactNode } from "react";

type Tab = "home" | "usage" | "meters" | "insights" | "settings";

const usage = [0.16, 0.12, 0.1, 0.13, 0.21, 0.37, 0.64, 0.91, 0.78, 0.61, 0.57, 0.66, 0.73, 0.68, 0.55, 0.48, 0.52, 0.77, 0.97, 0.83, 0.61, 0.46, 0.31, 0.21];
const days = [4.8, 5.4, 5.1, 6.0, 5.7, 5.8, 6.2];

function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const props = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
  const paths: Record<string, ReactNode> = {
    home: <><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1Z" /></>,
    chart: <><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" /><path d="m4 8 6-4 6 5 5-7" /></>,
    meter: <><rect x="3" y="4" width="18" height="16" rx="3" /><path d="M7 8h10M8 14h2m4 0h2m-8 3h10" /></>,
    spark: <path d="m13 2-8 12h6l-1 8 9-13h-6Z" />,
    settings: <><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.1 2.1-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56v.1h-3v-.1a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-2.1-2.1.06-.06A1.7 1.7 0 0 0 7.06 15 1.7 1.7 0 0 0 5.5 14H5.4v-3h.1a1.7 1.7 0 0 0 1.56-1.03 1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.1-2.1.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 11.73 4.8v-.1h3v.1a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.1 2.1-.06.06a1.7 1.7 0 0 0-.34 1.88A1.7 1.7 0 0 0 21 11h.1v3H21A1.7 1.7 0 0 0 19.4 15Z" /></>,
    bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></>,
    sun: <><circle cx="12" cy="12" r="4" /><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" /></>,
    plus: <><path d="M12 5v14M5 12h14" /></>,
    arrow: <path d="M5 12h14m-6-6 6 6-6 6" />,
    chevron: <path d="m9 18 6-6-6-6" />,
  };
  return <svg {...props}>{paths[name]}</svg>;
}

function Ring({ score = 71 }: { score?: number }) {
  const r = 94; const c = 2 * Math.PI * r;
  return <div className="ring-wrap"><svg className="energy-ring" viewBox="0 0 220 220"><defs><linearGradient id="energy" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#2aba72"/><stop offset=".56" stopColor="#7fcb67"/><stop offset="1" stopColor="#e1c951"/></linearGradient></defs><circle className="ring-base" cx="110" cy="110" r={r}/><circle className="ring-value" cx="110" cy="110" r={r} strokeDasharray={c} strokeDashoffset={c * (1-score/100)}/></svg><div className="ring-content"><span className="eyebrow">REMAINING UNITS</span><strong>142.6</strong><span className="units">units</span><div className="target"><span></span> 200 unit monthly target</div></div></div>
}

function BarChart({ values = usage }: { values?: number[] }) { return <div className="bar-chart">{values.map((value, i) => <div className="bar-col" key={i}><div className={`bar ${i > 16 && i < 21 ? "peak" : i > 6 && i < 16 ? "solar" : ""}`} style={{ height: `${value * 100}%` }} /></div>)}</div> }

function Home({ setTab, openAlerts }: { setTab: (t: Tab) => void; openAlerts: () => void }) {
 return <main className="screen home-screen">
  <header className="topbar"><div><p className="overline">TUESDAY, 20 AUG</p><h1>Good evening, Syed <span>👋</span></h1></div><button className="icon-button" onClick={openAlerts} aria-label="Open alerts"><Icon name="bell"/><i></i></button></header>
  <section className="hero"><div className="hero-copy"><span className="live-dot">Healthy consumption</span><h2>Your home is<br/><em>well balanced.</em></h2><p>You're on track to stay below this month's target.</p></div><Ring /></section>
  <div className="health-strip"><span className="health-score">82 <small>/ 100</small></span><div><b>Good Energy Usage</b><p>Usage is 7% below your weekly average</p></div><button onClick={() => setTab("insights")}>View outlook <Icon name="chevron" size={15}/></button></div><section className="flow-card"><div className="card-top"><div><span className="eyebrow">CURRENT POWER</span><h3>3.26 <small>kW</small></h3></div><span className="realtime"><b></b> Live</span></div><div className="flow-line"><div className="source solar-source"><span className="source-icon"><Icon name="sun" size={19}/></span><div><b>2.84 kW</b><small>Solar</small></div></div><div className="flow-arrow"><span></span><Icon name="arrow" size={17}/><span></span></div><div className="house"><div className="house-icon"><Icon name="home" size={22}/></div><b>Home</b></div><div className="flow-arrow wapda-arrow"><span></span><Icon name="arrow" size={17}/></div><div className="source grid-source"><span className="source-icon"><Icon name="spark" size={18}/></span><div><b>0.42 kW</b><small>WAPDA</small></div></div></div></section>
  <section className="section-head"><div><span className="eyebrow">TODAY'S USAGE</span><h2>8.9 <small>units</small></h2></div><button onClick={() => setTab("usage")}>View details <Icon name="chevron" size={17}/></button></section>
  <section className="usage-card"><div className="usage-stats"><div><span>Day</span><b>3.2 <small>units</small></b></div><div><span>Night</span><b>4.1 <small>units</small></b></div><div><span>Last 24h</span><b>8.9 <small>units</small></b></div></div><BarChart/><div className="chart-labels"><span>12am</span><span>6am</span><span>12pm</span><span>6pm</span><span>Now</span></div></section>
  <section className="mini-grid"><article><span className="mini-icon green"><Icon name="chart" size={17}/></span><span className="eyebrow">DAILY AVG.</span><b>5.8 <small>units</small></b><p>↓ 7% from last week</p></article><article><span className="mini-icon amber"><Icon name="spark" size={17}/></span><span className="eyebrow">200 UNIT DATE</span><b>14 <small>Sep</small></b><p>25 days remaining</p></article></section>
 </main>
}

function Usage() { const [range, setRange] = useState("7 Days"); return <main className="screen sub-screen"><header className="page-header"><div><span className="overline">ENERGY ANALYTICS</span><h1>Usage history</h1></div><button className="icon-button"><Icon name="chart" /></button></header><div className="segmented">{["Today", "7 Days", "30 Days"].map(x=><button className={range===x?"selected":""} onClick={()=>setRange(x)} key={x}>{x}</button>)}</div><section className="analytics-card"><div className="card-top"><div><span className="eyebrow">{range.toUpperCase()} CONSUMPTION</span><h2>39.0 <small>units</small></h2></div><span className="trend">↓ 6.2%</span></div><div className="week-chart">{days.map((v,i)=><div className="week-col" key={i}><span>{v}</span><div style={{height: `${v/6.8*142}px`}} className={i===6?"today-bar":""}></div><small>{["Wed","Thu","Fri","Sat","Sun","Mon","Tue"][i]}</small></div>)}</div></section><section className="summary-list"><h3>Consumption split</h3><div className="split-row"><span className="legend solar-dot"></span><p>Solar-supported usage</p><b>61%</b><em>23.8 units</em></div><div className="split-row"><span className="legend grid-dot"></span><p>WAPDA consumption</p><b>39%</b><em>15.2 units</em></div><div className="split-row"><span className="legend night-dot"></span><p>Night usage</p><b>46%</b><em>18.0 units</em></div></section></main> }

function Meters() { const [active, setActive] = useState(1); const [showEntry, setShowEntry] = useState(false); return <main className="screen sub-screen"><header className="page-header"><div><span className="overline">METER MANAGEMENT</span><h1>Your meters</h1></div><button className="round-add" onClick={()=>setShowEntry(!showEntry)}><Icon name="plus"/></button></header>{showEntry && <div className="entry-panel"><b>Record a reading</b><input placeholder="Enter current meter reading" type="number"/><button onClick={()=>setShowEntry(false)}>Save reading</button></div>}<p className="active-label"><span></span> CURRENTLY ACTIVE</p><MeterCard name="Meter 1" type="Analog" reading="59,460.6" remaining="139.4" active={active===1} onClick={()=>setActive(1)}/><p className="active-label inactive-label">INACTIVE</p><MeterCard name="Meter 2" type="Digital" reading="10,282.4" remaining="142.6" active={active===2} onClick={()=>setActive(2)}/><section className="switch-history"><h3>Switch history</h3><div><time>Today, 10:30 AM</time><p><span></span> Meter 1 activated</p></div><div><time>Yesterday, 7:15 PM</time><p><span></span> Meter 2 activated</p></div></section></main> }
function MeterCard({ name,type,reading,remaining,active,onClick }: any) {return <article className={`meter-card ${active?"active-meter":""}`} onClick={onClick}><div className="meter-title"><div className="meter-symbol"><Icon name="meter" size={22}/></div><div><h3>{name} <span>— {type}</span></h3><p><i className={active?"on":""}></i>{active?"Active supply":"Standby"}</p></div><Icon name="chevron" size={20}/></div><div className="meter-reading"><div><span>Current reading</span><b>{reading}</b></div><div><span>Remaining</span><b>{remaining} <small>units</small></b></div></div><div className="meter-footer"><span>Avg. <b>5.4 units/day</b></span><span>200 units: <b>16 Sep</b></span></div></article>}

function Insights() {return <main className="screen sub-screen"><header className="page-header"><div><span className="overline">PREDICTION ENGINE</span><h1>Energy outlook</h1></div><span className="pulse-badge">LIVE MODEL</span></header><section className="prediction-hero"><span className="eyebrow">ESTIMATED 200-UNIT DATE</span><h2>September 14</h2><p>25 days remaining at your current pace</p><div className="progress-line"><i></i></div><div className="prediction-stats"><div><b>5.8</b><span>Daily units</span></div><div><b>174</b><span>Monthly units</span></div><div><b>82</b><span>Health score</span></div></div></section><section className="insight-section"><div className="section-row"><h3>Smart insights</h3><button>See all</button></div><Insight icon="☀️" label="SOLAR INSIGHT" text="Solar covered most of your daytime load today." tone="green"/><Insight icon="↘" label="GOOD PROGRESS" text="Your average daily consumption has decreased for 3 consecutive days." tone="blue"/><Insight icon="!" label="WATCH" text="Nighttime consumption is 12% higher than your recent average." tone="amber"/></section></main>}
function Insight({icon,label,text,tone}:any){return <article className={`insight ${tone}`}><span className="insight-icon">{icon}</span><div><small>{label}</small><p>{text}</p></div><Icon name="chevron" size={18}/></article>}


function Alerts({ close }: { close: () => void }) { const alerts = [
  { tone: "amber", title: "Night usage is increasing", text: "4.1 units used after sunset — 12% above your 3-day average.", time: "Today, 8:42 PM", data: "+0.4 units" },
  { tone: "green", title: "Solar covered peak load", text: "Solar supplied 87% of your household load between 11 AM and 3 PM.", time: "Today, 3:06 PM", data: "2.84 kW peak" },
  { tone: "yellow", title: "Monthly threshold approaching", text: "You have 142.6 units remaining before your 200-unit target.", time: "Today, 9:00 AM", data: "71% remaining" },
  { tone: "red", title: "Reading reviewed", text: "Meter 2's latest reading was checked against your normal usage pattern.", time: "Yesterday, 7:16 PM", data: "No action needed" },
]; return <div className="alert-overlay"><section className="alerts-sheet"><header className="alerts-header"><div><span className="overline">ACTIVITY CENTER</span><h2>Alerts</h2></div><button className="close-alerts" onClick={close}>Done</button></header><div className="alert-summary"><span><Icon name="bell" size={19}/></span><div><b>2 things to keep an eye on</b><p>All readings and telemetry are synced.</p></div></div><div className="alert-list">{alerts.map(alert => <article className={`alert-card ${alert.tone}`} key={alert.title}><span className="alert-status"></span><div><small>{alert.time}</small><h3>{alert.title}</h3><p>{alert.text}</p><b>{alert.data}</b></div></article>)}</div></section></div> }

function Settings({ dark, setDark }: {dark:boolean; setDark:(v:boolean)=>void}) {return <main className="screen sub-screen"><header className="page-header"><div><span className="overline">PREFERENCES</span><h1>Settings</h1></div></header><section className="settings-group"><h3>Appearance</h3><div className="setting-row"><span className="settings-icon"><Icon name="sun"/></span><div><b>Dark mode</b><p>Easy on the eyes at night</p></div><button className={`toggle ${dark?"enabled":""}`} onClick={()=>setDark(!dark)}><i/></button></div></section><section className="settings-group"><h3>Household</h3>{[["Monthly unit target","200 units"],["Billing cycle","1st – 30th"],["Notifications","Usage & reading alerts"]].map(([a,b])=><div className="setting-row static" key={a}><div><b>{a}</b><p>{b}</p></div><Icon name="chevron" size={18}/></div>)}</section><section className="settings-group"><h3>Data</h3><div className="setting-row static"><div><b>Last synced</b><p>Just now · All data secure</p></div><span className="sync-dot"></span></div></section></main>}

export default function App() { const [tab, setTab] = useState<Tab>("home"); const [dark, setDark] = useState(false); const [alertsOpen, setAlertsOpen] = useState(false); const view = useMemo(()=> tab === "home"?<Home setTab={setTab} openAlerts={()=>setAlertsOpen(true)}/>:tab === "usage"?<Usage/>:tab === "meters"?<Meters/>:tab === "insights"?<Insights/>:<Settings dark={dark} setDark={setDark}/>,[tab,dark]); const nav = [["home","home","Home"],["usage","chart","Usage"],["meters","meter","Meters"],["insights","spark","Insights"],["settings","settings","Settings"]] as const; return <div className={`app-shell ${dark?"dark":""}`}><div className="desktop-frame">{view}<nav className="bottom-nav">{nav.map(([id,icon,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?"active":""}><Icon name={icon} size={20}/><span>{label}</span></button>)}</nav>{alertsOpen && <Alerts close={()=>setAlertsOpen(false)}/>}</div></div> }
